import type { Metadata } from "next";


import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Params } from "next/dist/server/request/params";

import NavBar from "./_components/navigation/NavBar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode, params: Params;
}>) {

  const {locale}: {locale: string} = await params

  return (
    <html lang={locale}>
      <body>
        <NavBar locale={locale} />
        {children}
      </body>
    </html>
  );
}
