import type { Metadata } from "next";



import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-icons/font/bootstrap-icons.css'
import "./globals.css";

import { Params } from "next/dist/server/request/params";

import NavBar from "./_components/navigation/NavBar";
import Footer from "./_components/footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode, params: Params;
}>) {

  const {locale}: {locale: string} = await params

  return (
    <html lang={locale}>
      <head>
   
      </head>
      <body className="flex flex-col items-center">
       
        <NavBar locale={locale} /> 
 
        {children}
        <Footer />
      </body>
    </html>
  );
}
